pik-piam/madrat

- DESCRIPTION
- R/toolAggregate.R
toolAggregate() fails with a somewhat unhelpful message when called with a tibble (instead of a data frame) as a relation matrix. tibbles are the default return for some newer read-in function (such as readxl:read_excel ), so I thought it was worth adding the option to use them by adding a conversion to data frame at the beginning of toolAggregate().
Minimal (non-)working example:
```
library(madrat)
library(magclass)
library(tibble)
x <- new.magpie(cells_and_regions = c('A', 'B', 'C', 'D'),
years = 2000,
names = 'dummy',
fill = 1:4)
relmatrix <- tibble(CountryCode = c('A', 'B', 'C', 'D'),
RegionCode = c('XX', 'XX', 'YY', 'YY'))
toolAggregate(x, rel = data.frame(relmatrix))
toolAggregate(x, rel = relmatrix)
```
Edit: formatting of example
> convert to data frame in toolAggregate()

- DESCRIPTION
- R/calcOutput.R
- R/readSource.R
- updated cache format from mz to rds in readSource to be consistent with calcOutput
- updated file permission settings for cache files
> Updated cache format in readSource

- DESCRIPTION
- R/getSources.R
- R/readSource.R
nonISO sources do not require anymore to write a convert function. Convert functions for these sources can now be deleted.
> No need for convertSource functions for non-ISO sources

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/downloadTau.R
- R/fingerprint.R
- R/setConfig.R
- README.md
- tests/testthat/test-fingerprint.R
- tests/testthat/test-readSource.R
- tests/testthat/test-toolAggregate.R
fingerprintFiles now uses the first 300 bytes of file content and the file's size for creating a fingerprint
> Hashing based on sample content and file size

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/fullEXAMPLE.R
- R/retrieveData.R
- R/toolMappingFile.R
- README.md
- tests/testthat/test-retrieveData.R
- vignettes/madrat-caching.Rmd
I applied some auto-formatting, so if actual changes are hard to see only look at commits after the initial formatting.
fullXYZ functions may now `return(list(tag = "mytag"))`, which will result in a filename like rev0_h12_test_mytag.tgz (with mytag as suffix)
> Optional filename tag for retrieveData

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/cacheArgumentsHash.R
- R/cacheName.R
- R/calcOutput.R
- R/findBottlenecks.R
- R/fingerprint.R
- R/getDependencies.R
- R/getISOlist.R
- R/getMadratGraph.R
- R/getMadratInfo.R
- R/installedMadratUniverse.R
- R/readSource.R
- R/regionscode.R
- R/robustOrder.R
- R/toolCountryFill.R
- R/toolISOhistorical.R
- R/toolOrderCells.R
- R/toolXlargest.R
- README.md
- tests/testthat/test-caching.R
- tests/testthat/test-robustOrder.R
- tests/testthat/test-toolOrderCells.R
Non-utf8 strings no longer lead to crashes (fixes #59) and sorting is now locale independent everywhere.
Added the internal robustOrder and robustSort functions, which are wrapper functions reound base::order and base::sort, but they convert character vectors to utf8 and always use local independent radix sort. In madrat these functions should be used instead of base::order and base::sort.
> Bugfix sort encoding

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/downloadSource.R
- R/readSource.R
- README.md
- man/downloadSource.Rd
- man/readSource.Rd
- tests/testthat/test-downloadSource.R
- tests/testthat/test-readSource.R
This PR deals with the following situation: A source is being downloaded (downloadSource) and in another parallel running R session that source is read (readSource). At the moment readSource would try to read the partially downloaded data and probably crash. With this PR readSource will recognize the running download and wait. downloadSource now writes into a folder called `<type>-downloadInProgress` and when the download is finished that folder is renamed to `<type>`.
> wait for running download in readSource

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/toolCountryFill.R
- README.md
- tests/testthat/test-toolCountryFill.R
fixed a warning in toolCountryFill which was triggered when an empty magclass object was expanded over all iso countries
> fixed a warning in toolCountryFill

- .buildlibrary
- .github/workflows/lucode2-check.yaml
- .pre-commit-config.yaml
- .zenodo.json
- DESCRIPTION
- R/vcat.R
- README.md
- man/isWrapperActive.Rd
- man/madratAttach.Rd
- man/setConfig.Rd
- tests/testthat/test-vcat-withMadratLogging.R
Calling `vcat(1, list())` was crashing, this PR fixes that. The key was just to deparse lists into character (see first change in vcat.R), the rest is just reducing cyclomatic complexity and linter stuff.
> fix vcat 'list cannot be handled by cat'

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/toolCountryFill.R
- README.md
Preserve the comment of a magpie object when returned from `toolCountryFill`. Addresses issue #136
> Preserve Comment in toolCountryFill

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/cacheCleanup.R
- R/downloadSource.R
- R/getConfig.R
- R/retrieveData.R
- R/setConfig.R
- R/toolCountryFill.R
- R/toolFillWithRegionAvg.R
- R/toolISOhistorical.R
- R/vcat.R
- README.md
- man/setConfig.Rd
- tests/testthat/test-retrieveData.R
- tests/testthat/test-vcat-withMadratLogging.R
- vcat should now properly react on suppressMessages or suppressWarnings statements
- removed diagnostics_full.log as it was containing partly misleading (supposedly) suppressed notes/warnings, use a higher verbosity instead to compute the corresponding, detailed information
- fixed linter warnings
> fixed vcat behavior

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/readSource.R
- README.md
- tests/testthat/test-caching.R
The latest madrat update introduced a new cache file format (list) which could lead to problems when loading old cache files with the new madrat via forcecache. This PR solves these issues.
> Compatibility to old cache files

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- Makefile
- R/getConfig.R
- README.md
I ran into a problem where `getConfig("tmpfolder")` did not exist. With this PR `getConfig` will create a folder before returning a path to it.
> create config folders

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- R/calcOutput.R
- R/toolAggregate.R
- README.md
- man/toolAggregate.Rd
- tests/testthat/test-calcOutput.R
- tests/testthat/test-toolAggregate.R
This PR comes with a bunch of improvements in toolAggregate and calcOutput:
* `toolAggregate` now works also in cases in which a relation map `rel` is not specified but the information can be retrieved from the subdimensions of the object
* setNames are now properly set in `toolAggregate` in cases in which the number of subdimensions in reduced during aggregation (e.g. mapping all subdimensions in dim = 1 to only a single spatial dimension)
* `calcOutput` can now aggregate cellular data to regions via `aggregate = TRUE` if the data comes with a spatial "country" subdimension containing all iso countries
*`calcOutput` can now aggregate directly to the spatial subdimensions of the returned object (similar to `toolAggregate`)
> Extended aggregation options in toolAggregate and calcOutput

- .buildlibrary
- .zenodo.json
- DESCRIPTION
- Makefile
- R/retrieveData.R
- README.md
- tests/testthat/test-retrieveData.R
retrieveData was writing to the diagnostics log (thus recreating the outputfolder) after the tgz was created and the outputfolder already deleted. This PR fixes that.
> fix retrieveData leftover folder/log

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/compareData.R
- README.md
This fix makes sure that the comparison of two cs4r files does not crash if one of the compared files contains NAs.
Right now, the line `diff <- max(abs(x - y)` could assign NA to `diff` in some cases, causing the subsequent evaluation to crash.
> fix bug in compareData.R

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getMadratMessage.R
- README.md
- tests/testthat/test-getputMadratMessage.R
improved support for readSource family of functions (read, convert, correct, download)
> improved support for readSource family of functions

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/calcOutput.R
- README.md
- man/calcOutput.Rd
Clarifies the usage of `try` parameter in `calcOutput`
> Fix typo in documentation of calcOutput

- .buildlibrary
- .pre-commit-config.yaml
- CITATION.cff
- DESCRIPTION
- R/visualizeDependencies.R
- README.md
In the updated version of visualizeDependenies, the vertices of the central functions are also colored according to the respective mr-package.
> improved visualizeDependencies

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/compareMadratOutputs.R
- R/downloadSource.R
- R/fingerprint.R
- R/pucAggregate.R
- R/readSource.R
- R/robustOrder.R
- R/toolstartmessage.R
- README.md
- man/compareMadratOutputs.Rd
- man/downloadSource.Rd
- man/fingerprint.Rd
- man/readSource.Rd
- man/robustOrder.Rd
- man/toolstartmessage.Rd
relevant changes are in https://github.com/pik-piam/madrat/commit/bb3871c038b3e5d709269f7f705040abde51d51c
I think the reason why codelabels were sometimes not working is because the tgz was generated from an existing puc. The puc includes an renv which is used to re-run the full function in a new R session, and codelabels were not moved over to this new R session. This PR fixes that.
> fix codelabels in pucAggregate

- .buildlibrary
- .github/workflows/check.yaml
- CITATION.cff
- DESCRIPTION
- R/toolGetMapping.R
- README.md
- tests/testthat/test-toolGetMapping.R
Okay this is a tricky one and there is probably a more elegant solution for this, but I didn't dig that deep. So I start with a bug report: 
`toolGetMapping` is designed to also be able to load mapping from packages that are installed via `devtools::load_all` but this sometimes fails.
- I add a new mapping to `mredgebuildings`
- I load build `mredgebuildings` and load it via `library` 
--> mapping found
- I add a new mapping to `mredgebuildings`
- I load `mredgebuildings` via `devtools::load_all` 
--> mapping not found
The problem is not reproducible if madrat is loaded via `load_all`
- I add a new mapping to `mredgebuildings`
- I load `mredgebuildings` via `devtools::load_all`
- I load `madrat` via `devtools::load_all` (unchanged code though)
--> mapping found
So when fixing this it …
> Extra attempt to find mapping with toolGetMapping

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/calcOutput.R
- README.md
- tests/testthat/test-calcOutput.R
Addresses https://github.com/pik-piam/madrat/issues/193
When `years` passed to `calcOutput` are not in produced data, a warning is thrown instead of an error and only the requested years available in the data are returned.
> allow missing years in calcOutput

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/fingerprint.R
- README.md
We have a couple of sources consisting of stylised parameters across a bunch of scenarios
```
$ ls -l /p/projects/rd3mod/inputdata/sources/industry_subsectors_specific/
total 66
-rw-rw-r-- 2 pehl rdev  494 Apr 21  2022 industry_specific_FE_limits.csv
-rw-rw-r-- 1 pehl rdev 4054 Aug 19  2022 specific_FE.csv
-rw-rw-r-- 1 pehl rdev 1017 Jun 17  2022 specific_material_alpha.csv
-rw-rw-r-- 1 pehl rdev  375 Mar 20  2023 specific_material_relative_change.csv
-rw-rw-r-- 1 pehl rdev 6021 Aug 19  2022 specific_material_relative.csv
```
It is entirely possible that these parameters are modified
1. without changing the file size, if a n-digit numbers are simply replaced by other n-digit numbers, or if the changes happen to add and remove the same number of characters, and
2. without changing anything …
> allow for fingerprint() to hash full files if a .fullhash file is present in the directory

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getMadratGraph.R
- README.md
Previously the regex `"tool([^( ]*)\\("` was in our R code. It matches "if (...) toolSomething(...)" as intended, but it also matched "tools::file_ext(...)", "mstools::toolSomething(...)" (substring "tools::toolSomething(" matched, which does not make sense), or "function_with_tool_anywhere(...)" (substring "tool_anywhere(" matched), frequently leading to false warnings e.g. when calling mstools tool functions via the recommended `::`. This PR fixes all of these cases.
> fix tool regex

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/initializeConfig.R
- README.md
- man/initializeConfig.Rd
This PR allows us to set environment variables to control which cache folder is used by madrat.
> init folder config from envvars

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/cacheName.R
- README.md
`madrat:::cacheName` failed if `getConfig("forcecache")` had length > 1 and the `mode == "puc"`. I changed the respective condition in the if clause though I would ask you, @tscheypidi, to check if you now expect the intended behaviour.
I had the problem that if I force cache for specific functions by passing a vector of function names, the failure lead to no cache file being written which depending on the settings lead to a failure overall.
> Bugfix: handle forcecache of length > 1

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/fingerprint.R
- README.md
This fixes the misleading warning: 
`Ignore corrupt hashCacheFile: "Error in if (nrow(files) == 0) files <- NULL : argument is of length zero`
Evaluating `if (nrow(files) == 0) files <- NULL` with `files = NULL` causes the error, because `nrow(NULL)` evaluates to `logical(0)` provoking the exception `"Ignore corrupt hashCacheFile"` in an unintended way.
> fix false warning for corrupt hash cache file

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/installedMadratUniverse.R
- README.md
Solves the mystery question of why `GDPuc::toolConvertGDP()` is sometimes hashed and sometimes not.
> extend installedMadratUniverse() to include all packages with madrat as a dependency

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- README.md
`igraph::as_undirected` is not exported in older igraph versions
> require igraph 2.1.1

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/convertTau.R
- R/readSource.R
- README.md
This PR simplifies the call stack if an error occurs in a read/convert function which is nicer for debugging, it's a minor refactoring. Currently we get this call stack:
```
1. └─madrat::readSource("Tau", "paper")
2.   └─madrat (local) .getData(type, subtype, subset, args, prefix, callString) at madrat/R/readSource.R:259:3
3.     ├─withr::with_dir(...) at madrat/R/readSource.R:147:5
4.     │ └─base::force(code)
5.     ├─madrat:::withMadratLogging(eval(parse(text = functionname))) at madrat/R/readSource.R:148:7
6.     │ └─base::withCallingHandlers(...) at madrat/R/withMadratLogging.R:36:3
7.     ├─base::eval(parse(text = functionname)) at madrat/R/withMadratLogging.R:36:3
8.     │ └─base::eval(parse(text = functionname))
9.     └─madrat:::convertTau(x = x)
```
and with this PR 3 and 4 are …
> simpler call stack

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/compareData.R
- README.md
Files are usually not different, so `compareData()` spends a whole lot of time summing up zeros.  Especially with the newly inflated transport data in REMIND.
Before
```
$ time inputdata-comparedata /p/projects/rd3mod/inputdata/output_1.27/rev7.19APT-2025-01-04_62eff8f7_remind.tgz /p/projects/rd3mod/inputdata/output_1.27/rev7.19APT-2025-01-04_62eff8f7_remind.tgz 2>/dev/null
real	11m59.506s
user	15m30.105s
sys	0m22.104s
```
After
```
$ time ./inputdata-comparedata /p/projects/rd3mod/inputdata/output_1.27/rev7.19APT-2025-01-04_62eff8f7_remind.tgz /p/projects/rd3mod/inputdata/output_1.27/rev7.19APT-2025-01-04_62eff8f7_remind.tgz 2>/dev/null
real	1m14.150s
user	0m44.468s
sys	0m47.173s
```
> compare file data of .csv files only if file hashes differ

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/getNonDefaultArguments.R
- README.md
on r-universe CI was failing to build under R 4.5.0dev: https://github.com/r-universe/pik-piam/actions/runs/13816310507/job/38650576681
I was able to reproduce this locally, `setdiff` didn't preserve names there, so I had to reformulate.
> fix for R 4.5.0dev

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/cachePut.R
- README.md
Even a SpatRaster backed by an on-disk source file was cached without referencing the source file (which was even copied to the madrat cache). This PR fixes this.
> fix SpatRaster caching

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/retrieveData.R
- R/setConfig.R
- R/vcat.R
- README.md
- man/setConfig.Rd
There are no known uses throughout Github repos (including pik-piam).
One disadvantage is now that we hard code the file name between `vcat` and `retrieveData`: 
https://github.com/pik-piam/madrat/blob/c6f192af5908dc77f1067b023035a2fa14d010ba/R/retrieveData.R#L185
https://github.com/pik-piam/madrat/blob/c6f192af5908dc77f1067b023035a2fa14d010ba/R/vcat.R#L75
> Deprecates setting the diagnostics config option to a filename.

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/calcOutput.R
- R/putMadratMessage.R
- README.md
- man/calcOutput.Rd
- man/madrat-package.Rd
- tests/testthat/test-calcOutput.R
- tests/testthat/test-getputMadratMessage.R
This PR adds a feature to `calcOutput` that allows users to write statistics on the unaggregated data to the status log. These statistics are supposed to be used to check whether there were changes in the input data between two runs of a pipeline.
Depends on https://github.com/pik-piam/mstools/pull/4
This PR includes:
- Adds a parameter to `calcOutput` and the code to actually calculate and write the statistic
- Adapts `putMadratMessage` to support structured madrat messages
- Adds tests for the new `calcOutput` feature
- Adapts existing `putMadratMessage` tests to also test for structured madrat messages
Open questions:
> Extend calcOutput to write statistics to status log

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/calcOutput.R
- README.md
- man/calcOutput.Rd
- tests/testthat/test-calcOutput.R
This only moves `outputStatistics` after `...` and adds a trivial test to ensure we notice a regression.
> Fix partialArgumentMatch of output to outputStatistics

- .buildlibrary
- CITATION.cff
- DESCRIPTION
- R/setConfig.R
- README.md
- man/setConfig.Rd
- tests/testthat/test-config.R
This PR changes `setConfig` so that when using a positional parameter instead of a named parameter no config fields will change.
> Prevent accidental setting of positional arguments in setConfig 

- .buildlibrary
- .github/workflows/check.yaml
- CITATION.cff
- DESCRIPTION
- R/calcOutput.R
- README.md
- man/calcOutput.Rd
- **allow skipping clean_magpie in calcOutput**
clean_magpie would remove the id subdim from regional data, but in mrdownscale the id subdim is expected
> allow skipping clean_magpie in calcOutput
