pik-piam/madrat

DESCRIPTION, R/fullEXAMPLE.R, R/retrieveData.R
with the new "dev" argument it is now possible to distinguish developments lines which are based on the same revision number.
=> added "dev" argument which introduces a developer suffix to retrieveData

DESCRIPTION, R/calcOutput.R, R/initializeConfig.R, R/readSource.R, R/retrieveData.R, R/setConfig.R
- added debug setting which will force try=TRUE on all calculations
- malformed cache files will no longer interrupt calculations, instead cache file will be ignored
=> added debug setting and improved cache file handling

DESCRIPTION, R/toolAggregate.R
bugfix in toolAggregate for cases in which subdimensions over which should be aggregated appear on input as well as output side
=> bugfix in toolAggregate

DESCRIPTION, R/toolAggregate.R, tests/testthat/test-toolAggregate.R
- it is now possible to aggregate to more than one column at once (e.g. regional + global)
- automatic "from" selection is now checking which column actually fits the input data.
- adapted "to" selection to new approach for "from" to work as before (take adjacent column to "from" as "to", if nothing else is known)
=> prepared toolAggregate to better work with multi-column mappings

DESCRIPTION, R/toolTimeSpline.R
=> Bugfix creation of negative values in spline function

.zenodo.json, DESCRIPTION, R/toolTimeSpline.R, README.md
toolTimeSpline did not work for case of 67420 cells. Added if statement for this special case
=> Added option of 67420 cells in toolTimeSpline

.Rbuildignore, .buildlibrary, .zenodo.json, DESCRIPTION, R/calcOutput.R, R/toolAggregate.R, R/toolConvertMapping.R, R/toolGetMapping.R, README.md, tests/testthat/test-calcOutput.R, tests/testthat/test-readSource.R
- added rds support in toolGetMapping, toolConvertMapping, toolAggregate and calcOutput
- toolAggregate can read now all file formats supported by toolGetMapping
- tests which need an internet connection are now skipped if no connection is available
=> Added rds mapping files support

.buildlibrary, .zenodo.json, DESCRIPTION, R/toolCountry2isocode.R, README.md
- warning messages use now the real inputs, not a lowercase version of it 
- function does not distinguish anymore complex and simple cases
=> improved toolCountry2isocode

.buildlibrary, .zenodo.json, DESCRIPTION, NAMESPACE, R/findBottlenecks.R, R/fullEXAMPLE.R, README.md, tests/testthat/test-findBottlenecks.R
=> added findBottlenecks function and corresponding tests

.buildlibrary, .zenodo.json, DESCRIPTION, R/getCalculations.R, R/getMadratGraph.R, README.md
small performance tweak in getCalculations and getMadratGraph relevant for future updates
=> getCalculations can now filter several types at once

.buildlibrary, .zenodo.json, DESCRIPTION, R/cacheArgumentsHash.R, README.md
- generated cache was depending on locale (as ordering of lower and upper case arguments is handled differently)
- comparison of arguments was not working properly
=> bugfixes in cacheArgumentsHash

.Rbuildignore, .buildlibrary, .zenodo.json, DESCRIPTION, R/setConfig.R, README.md
- add .git directory to .Rbuildignore
=> fix typo in setConfig() documentation

.buildlibrary, .zenodo.json, DESCRIPTION, R/cacheName.R, R/cachePut.R, R/calcOutput.R, R/downloadSource.R, R/fingerprint.R, R/prepFunctionName.R, README.md, tests/testthat/test-fingerprint.R
Wrap fingerprint in tryCatch, so calculation can continue if fingerprinting is broken.
Also fixes #60
=> tryCatch fingerprint

.buildlibrary, .zenodo.json, DESCRIPTION, R/cacheArgumentsHash.R, R/cacheName.R, R/fingerprint.R, README.md, tests/testthat/test-caching.R, tests/testthat/test-fingerprint.R
bugfixing incorrect/missing argumentHash if fingerprint hashing failed but forcecache was active
=> bugfixing incorrect/missing argumentHash if fingerprint hashing failed

.buildlibrary, .zenodo.json, DESCRIPTION, R/cacheArgumentsHash.R, R/fingerprint.R, R/getNonDefaultArguments.R, README.md, tests/testthat/test-getNonDefaultArguments.R, tests/testthat/test-retrieveData.R
relevant to show original order in log file
=> added sort argument in getNonDefaultArguments

.buildlibrary, .zenodo.json, DESCRIPTION, README.md, tests/testthat/test-config.R
This should fix failing checks on CRAN (https://cran.r-project.org/web/checks/check_results_madrat.html)
=> normalizePath in test-config.R

.buildlibrary, .zenodo.json, DESCRIPTION, R/fullEXAMPLE.R, R/retrieveData.R, README.md, vignettes/madrat.Rmd
- updated vignette and fullEXAMPLE
=> - retrieveData calls now fullFunction from output folder

.buildlibrary, .zenodo.json, DESCRIPTION, R/compareData.R, README.md, man/compareData.Rd, tests/testthat/test-config.R
=> extension compareData function

.buildlibrary, .zenodo.json, DESCRIPTION, R/toolCountryFill.R, R/toolFillWithRegionAvg.R, README.md, man/toolFillWithRegionAvg.Rd
improved warning/note messages in toolFillWithRegionAvg and toolCountryFill
=> improved warning/note messages

.buildlibrary, .zenodo.json, DESCRIPTION, R/calcOutput.R, README.md, man/calcOutput.Rd
renamed argument na_warning to warnNA to ease search for warnings in log files
=> renamed argument na_warning to warnNA 

.buildlibrary, .zenodo.json, DESCRIPTION, R/retrieveData.R, README.md
this fix prevents the snapshot function from triggering an error message in cases in which the preflight checks of this function find an inconsistency
=> fix a bug in puc creation

.buildlibrary, .zenodo.json, DESCRIPTION, R/toolAggregate.R, README.md
fixing a problem with weighted aggregation of bilateral data (weights were not properly mapped to corresponding dimensions - fixed via use of identical set names)
=> bugfix in toolAggregate 

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, R/addMapping.R, R/calcOutput.R, R/pucAggregate.R, R/retrieveData.R, R/toolAggregate.R, README.md, man/pucAggregate.Rd, tests/testthat/test-calcOutput.R
* added bilateral data support in `calcOutput`
* added a check in `addMapping`
* added argument `strict` in `pucAggregate` and set it to `FALSE` by default
* performance tweak in `toolAggregate` for instances in which all values in a column are NA
=> support for bilateral data + fixes

.buildlibrary, .github/workflows/check.yaml, .zenodo.json, DESCRIPTION, Makefile, R/calcOutput.R, R/calcTauTotal.R, README.md, tests/testthat/test-calcOutput.R
- bugfix in map calculations in calcOutput
- added small number to weight in calcTauTotal to avoid loss of information during aggregation
=> bugfix in map calculations in calcOutput

.buildlibrary, .zenodo.json, DESCRIPTION, R/retrieveData.R, README.md, man/retrieveData.Rd, tests/testthat/test-puc.R
major version increment due to change in defaults
=> changed default cachetype in retrieveData from rev to def

.buildlibrary, CITATION.cff, DESCRIPTION, R/retrieveData.R, README.md, cran-comments.md
removed "..." from arguments to be sent to full function
=> bugfix in retrieveData

.buildlibrary, CITATION.cff, DESCRIPTION, R/fingerprint.R, README.md
not all files were written to hashCache file
=> bugfix in fingerprint function

.buildlibrary, CITATION.cff, DESCRIPTION, R/cacheName.R, R/isWrapperActive.R, R/pucAggregate.R, README.md, tests/testthat/test-puc.R
During pucAggregate the note "forced cache does not match fingerprint" comes up, but is misleading there, so this PR suppresses it in that case
=> pucAggregate no forced cache note

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/toolAggregate.R, README.md, man/toolAggregate.Rd, tests/testthat/test-toolAggregate.R
- close #214
- if `zeroWeight == "setNA"`, replace every 0 in the weight sum by NA, such that the aggregated value is NA as well
=> add setNA option to toolAggregate

.buildlibrary, .github/workflows/check.yaml, CITATION.cff, DESCRIPTION, R/toolISOhistorical.R, README.md, tests/testthat/test-toolISOhistorical.R
add small value to weight in toolAggregate call in toolISOhistorical to remove warning. 
adjust test to test for equal instead of identical
=> fix toolAggregate warning in toolISOHistorical

.buildlibrary, CITATION.cff, DESCRIPTION, R/readSource.R, README.md
=> fix readSource.R roxygen
